language: python
python:
- 3.6
services:
- docker
install:
- docker build -t max-audio-sample-generator .
- docker run -it -d -p 5000:5000 max-audio-sample-generator
- sleep 10
before_script:
- pip install pytest requests scipy numpy
script:
- pytest tests/test.py
